# Generated by Django 3.0.7 on 2020-07-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b01',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b02',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b03',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b04',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b05',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b06',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b07',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b08',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b09',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b10',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b11',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='b12',
        ),
        migrations.RemoveField(
            model_name='learnerdp_has_termsubjectdp',
            name='cp_observation',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='baremeNoteCritere',
            field=models.SmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_marksup_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nb_stud_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='cp_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='f13_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='f14_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='f15_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='jgt_obsersation',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_note_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s13_obsersation',
            field=models.CharField(max_length=720, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_note_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s14_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_note_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerdp_has_termsubjectdp',
            name='s15_obsersation',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='f13_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='f14_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='f15_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_note_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_note_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_note_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_note_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_note_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_note_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s13_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_note_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_note_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_note_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_note_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_note_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_note_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s14_obsersation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_note_a',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_note_b',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_note_c',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_note_d',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_note_e',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_note_f',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_obsersation',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f01_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f02_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f03_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f04_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f05_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f06_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f07_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f08_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f09_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f10_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f11_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='f12_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s01_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s02_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s03_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s04_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s05_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s06_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s07_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s08_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s09_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s10_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s11_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerdp_has_termsubjectdp',
            name='s12_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f01_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f02_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f03_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f04_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f05_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f06_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f07_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f08_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f09_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f10_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f11_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='f12_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s01_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s02_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s03_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s04_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s05_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s06_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s07_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s08_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s09_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s10_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s11_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s12_observation',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.CreateModel(
            name='student_has_termsubjeval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mod_version', models.SmallIntegerField(default=0)),
                ('ref_term', models.SmallIntegerField()),
                ('note', models.FloatField(null=True)),
                ('crit_a', models.SmallIntegerField(null=True)),
                ('crit_b', models.SmallIntegerField(null=True)),
                ('crit_c', models.SmallIntegerField(null=True)),
                ('crit_d', models.SmallIntegerField(null=True)),
                ('crit_e', models.SmallIntegerField(null=True)),
                ('crit_f', models.SmallIntegerField(null=True)),
                ('observation', models.CharField(max_length=360, null=True)),
                ('ref_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='larcauth.evaluation')),
                ('ref_idstudent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='larcauth.student')),
            ],
        ),
    ]
