# Generated by Django 3.0.7 on 2020-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0003_auto_20200724_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerpei_has_termsubjectpei',
            name='s15_observation',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
