# Generated by Django 3.0.7 on 2020-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0004_auto_20200724_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerdp_has_termsubjectdp',
            old_name='cp_obsersation',
            new_name='cp_observation',
        ),
        migrations.RenameField(
            model_name='learnerdp_has_termsubjectdp',
            old_name='s14_obsersation',
            new_name='s14_observation',
        ),
        migrations.RenameField(
            model_name='learnerdp_has_termsubjectdp',
            old_name='s15_obsersation',
            new_name='s15_observation',
        ),
    ]
