# Generated by Django 3.0.7 on 2020-07-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0005_auto_20200724_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerdp_has_termsubjectdp',
            old_name='s13_obsersation',
            new_name='s13_observation',
        ),
    ]
