# Generated by Django 3.0.7 on 2020-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larcauth', '0009_auto_20200728_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='all_grades',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='all_grades_a',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='all_grades_b',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='all_grades_c',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='all_grades_d',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='all_grades_e',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='all_grades_f',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
